### ISSUE TITLE
Cant deploy 8.0/stable on AWS EKS 

### ISSUE THREAD

**Issue by misohu** [canonical/mysql-k8s-operator#237]
Hi I am trying to deploy mysql as part of our [mlflow bundle](https://charmhub.io/mlflow) to AWS EKS 1.23.

## Steps to reproduce

1. I deploy AWS EKS with my aws cli ... I use 1.23 
```
eksctl create cluster --name kubeflow --region eu-central-1 --ssh-access --ssh-public-key=kubeflow-example-keypair --node-type=t2.2xlarge --nodes=2 --node-volume-size=100 --node-volume-type=gp2 --version=1.23
```
2. I enable EBS CSI default storage class with [this docs](https://docs.aws.amazon.com/eks/latest/userguide/managing-ebs-csi.html#adding-ebs-csi-eks-add-on)

3. I create the contorller and model 
```
sudo snap install juju --classic
juju add-k8s kubeflow 
juju bootstrap --no-gui kubeflow kubeflow-controller 
juju add-model kubeflow
```

4. I deploy mlflow bundle with 
```
juju deploy mlflow --channel=2.1/edge --trust
```
This is the bundle file 
```
bundle: kubernetes
name: mlflow
docs: https://discourse.charmhub.io/t/mlflow-docs-index/10836
applications:
  mlflow-minio:
    charm: minio
    channel: ckf-1.7/edge
    scale: 1
    trust: true
    _github_repo_name: minio-operator
  mlflow-mysql:
    charm: mysql-k8s
    channel: 8.0/stable
    series: jammy
    scale: 1
    trust: true
    _github_repo_name: mysql-k8s-operator
  mlflow-server:
    charm: mlflow-server
    channel: latest/edge
    scale: 1
    trust: true
    _github_repo_name: mlflow-operator
relations:
- [mlflow-server, mlflow-minio]
- [mlflow-server, mlflow-mysql]
```

## Expected behavior
I want mysql to go to active state

## Actual behavior

Mysql ends up in blocked state
![image](https://github.com/canonical/mysql-k8s-operator/assets/17260453/06c246f3-5649-411c-97b2-5ea49595b3b4)

## Versions

Operating system: should be Amazon Linux 2 AMIs

Juju CLI: 2.9.42-ubuntu-amd64

Juju agent: 
```
Model     Controller           Cloud/Region           Version  SLA          Timestamp
kubeflow  kubeflow-controller  kubeflow/eu-central-1  2.9.42   unsupported  09:16:31+02:00

App            Version                Status   Scale  Charm          Channel       Rev  Address         Exposed  Message
mlflow-minio   res:oci-image@1755999  active       1  minio          ckf-1.7/edge  186  10.100.157.154  no       
mlflow-mysql                          waiting      1  mysql-k8s      8.0/stable     75  10.100.54.95    no       installing agent
mlflow-server                         waiting      1  mlflow-server  latest/edge   288  10.100.204.182  no       installing agent

Unit              Workload  Agent  Address         Ports              Message
mlflow-minio/0*   active    idle   192.168.33.73   9000/TCP,9001/TCP  
mlflow-mysql/0*   blocked   idle   192.168.51.96                      Unable to configure instance
mlflow-server/0*  waiting   idle   192.168.60.176                     Waiting for relational-db relation data
```

AWS EKS: 1.23

## Log output

Juju debug log: 
[debug-log.log](https://github.com/canonical/mysql-k8s-operator/files/11685117/debug-log.log)

## Additional context

On microk8s 1.23 no problems
